2015/08/17 02:16:47 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\php\yii\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\php\yii\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\php\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\php\yii\framework\base\CModule.php(523): CModule->getComponent('bootstrap')
#3 C:\xampp\php\yii\framework\base\CApplication.php(163): CModule->preloadComponents()
#4 C:\xampp\php\yii\framework\YiiBase.php(125): CApplication->__construct('C:\\xampp\\htdocs...')
#5 C:\xampp\php\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\avaliacao360\app\index.php(13): YiiBase::createWebApplication('C:\\xampp\\htdocs...')
#7 {main}
REQUEST_URI=/avaliacao360/app/index.php
---
2015/08/17 02:20:39 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\php\yii\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\php\yii\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\php\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\php\yii\framework\base\CModule.php(523): CModule->getComponent('bootstrap')
#3 C:\xampp\php\yii\framework\base\CApplication.php(163): CModule->preloadComponents()
#4 C:\xampp\php\yii\framework\YiiBase.php(125): CApplication->__construct('C:\\xampp\\htdocs...')
#5 C:\xampp\php\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\avaliacao360\app\index.php(13): YiiBase::createWebApplication('C:\\xampp\\htdocs...')
#7 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php
---
2015/08/17 02:20:43 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\php\yii\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\php\yii\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\php\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\php\yii\framework\base\CModule.php(523): CModule->getComponent('bootstrap')
#3 C:\xampp\php\yii\framework\base\CApplication.php(163): CModule->preloadComponents()
#4 C:\xampp\php\yii\framework\YiiBase.php(125): CApplication->__construct('C:\\xampp\\htdocs...')
#5 C:\xampp\php\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\avaliacao360\app\index.php(13): YiiBase::createWebApplication('C:\\xampp\\htdocs...')
#7 {main}
REQUEST_URI=/avaliacao360/app/
---
2015/08/17 12:58:34 [error] [exception.CException] exception 'CException' with message 'A propriedade "CHttpRequest.basePath" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\views\site\login.php(11): CComponent->__get('basePath')
#1 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#2 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#5 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(89): CController->render('login', Array)
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=
---
2015/08/18 01:54:53 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.textField" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2529): CComponent->__get('textField')
#1 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(LoginForm), 'textField')
#2 C:\xampp\php\yii\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(LoginForm), 'textField', Array)
#3 C:\xampp\php\yii\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(LoginForm), 'textField', Array)
#4 [internal function]: CActiveForm->textField(Object(LoginForm), 'textField', Array)
#5 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1293): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1152): TbActiveForm->verticalGroup(Array, Object(LoginForm), 'textField', Array)
#7 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(389): TbActiveForm->customFieldGroupInternal(Array, Object(LoginForm), 'textField', Array)
#8 C:\xampp\htdocs\avaliacao360\app\protected\views\site\login.php(40): TbActiveForm->textFieldGroup(Object(LoginForm), 'textField')
#9 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#10 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#11 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(89): CController->render('login', Array)
#14 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#15 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#19 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#20 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/
---
2015/08/20 13:59:00 [error] [php] include(Funcionario.php): failed to open stream: No such file or directory (C:\xampp\php\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\components\UserIdentity.php(19): spl_autoload_call()
#1 C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php(49): UserIdentity->authenticate()
#2 C:\xampp\php\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\php\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 C:\xampp\php\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(85): LoginForm->validate()
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\php\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\php\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
in C:\xampp\htdocs\avaliacao360\app\protected\components\UserIdentity.php (19)
in C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php (49)
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (85)
2015/08/20 14:00:47 [error] [exception.CException] exception 'CException' with message 'A propriedade "UserIdentity.email" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\components\UserIdentity.php(21): CComponent->__get('email')
#1 C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php(49): UserIdentity->authenticate()
#2 C:\xampp\php\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\php\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\php\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(85): CModel->validate()
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:07:22 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:07:22 [warning] [application] Failed to set unsafe attribute "password" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:07:22 [warning] [application] Failed to set unsafe attribute "rememberMe" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:07:22 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.username" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2529): CComponent->__get('username')
#1 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(LoginForm), 'username')
#2 C:\xampp\php\yii\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(LoginForm), 'username', Array)
#3 C:\xampp\php\yii\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(LoginForm), 'username', Array)
#4 [internal function]: CActiveForm->textField(Object(LoginForm), 'username', Array)
#5 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1293): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1152): TbActiveForm->verticalGroup(Array, Object(LoginForm), 'username', Array)
#7 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(389): TbActiveForm->customFieldGroupInternal(Array, Object(LoginForm), 'username', Array)
#8 C:\xampp\htdocs\avaliacao360\app\protected\views\site\login.php(29): TbActiveForm->textFieldGroup(Object(LoginForm), 'username')
#9 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#10 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#11 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(89): CController->render('login', Array)
#14 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#15 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#19 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#20 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:08:52 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:08:52 [warning] [application] Failed to set unsafe attribute "password" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:08:52 [warning] [application] Failed to set unsafe attribute "rememberMe" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:19:19 [error] [exception.CException] exception 'CException' with message 'A propriedade "UserIdentity._id" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\components\UserIdentity.php(30): CComponent->__set('_id', '1')
#1 C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php(46): UserIdentity->authenticate()
#2 C:\xampp\php\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('senha', Array)
#3 C:\xampp\php\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'senha')
#4 C:\xampp\php\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(85): CModel->validate()
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:20:06 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.rememberMe" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php(61): CComponent->__get('rememberMe')
#1 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(85): LoginForm->login()
#2 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#3 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#8 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:20:47 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Sua requisição é inválida.' in C:\xampp\php\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('funcionario/upd...')
#10 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=funcionario/update
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:21:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Você não está autorizado a realizar essa operação.' in C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Voc\xC3\xAA n\xC3\xA3o est\xC3...')
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('funcionario/adm...')
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=funcionario/admin
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=funcionario/index
---
